name: redurx_persist_web
description: ReduRx Persist Web Integration with custom storage engines
version: 0.9.0
homepage: https://github.com/feilfeilundfeil/redurx_persist/tree/master/packages/redurx_persist_web
authors:
- Feil Feil & Feil GmbH <github@account.ffuf.de>
- David Wimmer <david.wimmer@ffuf.de>
- Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=1.24.0 <3.0.0"

dependencies:
  #redurx_persist: "^0.9.0"
  redurx_persist:
    git:
      url: git@github.com:feilfeilundfeil/redurx_persist.git
      path: packages/redurx_persist

