name: redurx_persist_web
description: ReduRx Persist Web Integration with custom storage engines
version: 0.1.0
#homepage: https://github.com/Cretezy/redurx_persist/tree/master/packages/redurx_persist_web
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=1.24.0 <3.0.0"

dependencies:
  redurx_persist: "^0.1.0"

# Used for development
dependency_overrides:
  redurx_persist:
    path: ../redurx_persist
