name: redurx_persist
description: Persist ReduRx State with custom storage engines and serializers
version: 0.9.0
homepage: https://github.com/feilfeilundfeil/redurx_persist/tree/master/packages/redurx_persist
authors:
- Feil Feil & Feil GmbH <github@account.ffuf.de>
- David Wimmer <david.wimmer@ffuf.de>
- Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  redurx: "^1.0.0"
  synchronized: "^1.5.0"
  meta: "^1.1.0"

dev_dependencies:
  test: "^1.0.0"
